### ISSUE TITLE
Mint build is broken.

### ISSUE THREAD

**Issue by ebozduman** [minio/mint#118] opened 2017-08-21 22:30 UTC
Here is the error message:
```
npm WARN gulp-babel@7.0.0 requires a peer of babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc but none was installed.
npm WARN bin@1.0.0 No description
npm WARN bin@1.0.0 No repository field.
npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "--prefix" "/mint/run/core/minio-js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! evp_bytestokey@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the evp_bytestokey@1.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the evp_bytestokey package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs evp_bytestokey
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls evp_bytestokey
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mint/npm-debug.log
The command '/bin/sh -c /mint/build/js/install.sh' returned a non-zero code: 1
```

**Comment by ebozduman** [comment] 2017-08-21 22:41
This is the /mint/npm-debug.log file's end:

```
:
:
:
51512 silly install printInstalled
51513 warn gulp-babel@7.0.0 requires a peer of babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc but none was installed.
51514 verbose If you need help, you may report this error at:
51514 verbose     <https://github.com/npm/npm/issues>
51515 warn bin@1.0.0 No description
51516 verbose If you need help, you may report this error at:
51516 verbose     <https://github.com/npm/npm/issues>
51517 warn bin@1.0.0 No repository field.
51518 verbose If you need help, you may report this error at:
51518 verbose     <https://github.com/npm/npm/issues>
51519 verbose stack Error: evp_bytestokey@1.0.1 install: `node-gyp rebuild`
51519 verbose stack Exit status 1
51519 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
51519 verbose stack     at emitTwo (events.js:106:13)
51519 verbose stack     at EventEmitter.emit (events.js:191:7)
51519 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
51519 verbose stack     at emitTwo (events.js:106:13)
51519 verbose stack     at ChildProcess.emit (events.js:191:7)
51519 verbose stack     at maybeClose (internal/child_process.js:891:16)
51519 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
51520 verbose pkgid evp_bytestokey@1.0.1
51521 verbose cwd /mint
51522 error Linux 4.10.0-32-generic
51523 error argv "/usr/bin/nodejs" "/usr/bin/npm" "--prefix" "/mint/run/core/minio-js" "install"
51524 error node v6.11.2
51525 error npm  v3.10.10
51526 error code ELIFECYCLE
51527 error evp_bytestokey@1.0.1 install: `node-gyp rebuild`
51527 error Exit status 1
51528 error Failed at the evp_bytestokey@1.0.1 install script 'node-gyp rebuild'.
51528 error Make sure you have the latest version of node.js and npm installed.
51528 error If you do, this is most likely a problem with the evp_bytestokey package,
51528 error not with npm itself.
51528 error Tell the author that this fails on your system:
51528 error     node-gyp rebuild
51528 error You can get information on how to open an issue for this project with:
51528 error     npm bugs evp_bytestokey
51528 error Or if that isn't available, you can get their info via:
51528 error     npm owner ls evp_bytestokey
51528 error There is likely additional logging output above.
51529 verbose exit [ 1, true ]
```

**Comment by NitishT** [comment] 2017-08-22 01:40
Mint build is working on local computer and on Travis, see https://github.com/minio/mint/pull/117. The failure may be Travis CI issue. Closing this as `working as intended`

**Comment by NitishT** [comment] 2017-08-22 03:00
Reopening until we find a plausible reason for why the Travis build failed.

**Comment by NitishT** [comment] 2017-08-22 03:29
Looks like `evp_bytestokey@1.0.1` is the issue. @krishnasrinivas @balamurugana can weigh in here. 

For the last build the version used was `evp_bytestokey@1.0.0` (https://travis-ci.org/minio/mint/builds/265726277) which worked fine. 

With `evp_bytestokey@1.0.1` (as in above logs) the build failed. But when I triggered the Travis build again (https://travis-ci.org/minio/mint/builds/266961004) it used `evp_bytestokey@1.0.2` as a new release was made recently.

**Closed** 2017-08-22 03:33 UTC
Labels: working as intended
